ansible_python_interpreter: /usr/bin/python3
ansible_host: "{{ lookup('env', 'REMOTE_HOST') }}"
ansible_user: "{{ lookup('env', 'USER') }}"
ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_FILE') }}"
deploy_dir: "{{ lookup('env', 'DEPLOYMENT_DIRECTORY') }}"
